### ISSUE TITLE
Awesome config, thank you very much

### ISSUE THREAD

**Issue by edyehoshua** [gseidler/tmux-statusline-gruvbox-dark#1]
Congratulations for the theme, I love it!
I just have a question. I don't know what I did wrong but for the status bar left it shows this
![Screenshot_2020-12-21_10-42-40](https://user-images.githubusercontent.com/60485595/102788825-9f70b680-4379-11eb-8d56-015ff58c9c6b.png)
Instead of the name, it shows a 0 and the same goes for windows bars. How can I fix it? And you can also see a small difference in the bg color

**Comment by gseidler** [comment]
The difference in screen color is probably because your terminal emulator isn't configured for Truecolor.
Did you name your session when you created it? (tmux new -s NAME)
I'm using tmux 3.1 on both my machines.
These are my screenshots for iTerm2 Mac and Terminal Ubuntu:
<img width="187" alt="Screen Shot 2020-12-21 at 20 42 54" src="https://user-images.githubusercontent.com/13736955/102832528-6e21d600-43cd-11eb-9dae-b327ce0cf409.png">
<img width="207" alt="Screen Shot 2020-12-21 at 20 41 20" src="https://user-images.githubusercontent.com/13736955/102832533-724df380-43cd-11eb-91bd-2abd3ca078e3.png">

**Comment by edyehoshua** [comment]
Ok I get it. I didn't name my session, thanks for the tip. I ended up changing colours and modifying your theme a bit part of the day. Anyway I've learned a lot and your theme is my favorite.

**Comment by gseidler** [comment]
Cool! Have fun!
